- name: Task1
  hosts: 127.0.0.1
  become: true
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest

    - name: Settings nginx
      template:
        remote_src: true
        src: /etc/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf

