- name: deploy httpd on container
  hosts: 127.0.0.1
  become: true
  tasks:
    - name: Install pacages
      ansible.builtin.apt:
        name:
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest

    - name: Install docker
      ansible.builtin.apt:
        name: docker.io
        state: latest

    - name: Docker Module for Python
      ansible.builtin.pip:
        name: docker
        state: present

    - name: start docker
      service:
        name: docker
        state: started

    - name: pull image
      community.docker.docker_image:
        name: httpd:latest
        source: pull

    - name: run httpd container
      community.docker.docker_container:
        name: httpd
        image: httpd:latest
        state: started
