- name: Install MySQL and settings
  hosts: 127.0.0.1
  become: true
  tasks:
    - name: Install MySQL
      apt:
        name: mariadb-server
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: true

    - name: Install modules pip
      apt:
        name: python3-pip
        state: present

    - name: Install pymysql
      pip:
        name: pymysql
        state: present

    - name: Create mysql user
      community.mysql.mysql_user:
        name: 'sql_user'
        password: '12345sql'
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create config file cnf
      copy:
        dest: /root/.my.cnf
        mode: '640'
        content: |
          [client]
          user='sql_user'
          password='12345sql'

    - name: Create DB
      community.mysql.mysql_db:
        name: 'my_db'
        state: present
